### ISSUE TITLE
コード追加のお願い（テキスト教材：管理者画面）

### ISSUE THREAD

**Issue by kyokucho1989** [yoshitokamizato/Gyakuten#125]
> 
> gemをインストールします。
> bundle install
> gemのインストールが完了したら、Active Adminに必要なファイルをインストールします。
> 
> rails generate active_admin:install
> マイグレートを実行します。
> 
> bundle exec rake db:migrate

この場合、
```
undefined method `devise' for AdminUser (call 'AdminUser.connection' to establish a connection):Class (NoMethodError)
```
というエラーが生じました。

調べるとmigrateの前に
```
rails g devise install
```
をしないといけないそうです。
https://qiita.com/ryouzi/items/9c5324ba567109ab2a22

そういうわけで、
`bundle install`と　`rails generate active_admin:install`
の間に
`rails g devise install`
の記述をお願いします。

**Comment by kyokucho1989** [comment]
あと、同じページの
``` ruby
class CreateDataTests < ActiveRecord::Migration[5.2]
  def change
    create_table :data_tests do |t|
      t.string :name
      t.integer :age
      t.string :address
      t.timestamps
    end
  end
end
```
ですが、これは

```ruby 
class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.string :name
      t.integer :age
      t.string :address
      t.timestamps
    end
  end
end
```

だと思います。

**Comment by T-Tsujii** [comment]
ありがとうございます！こちらは修正完了しました！
