### ISSUE TITLE
テキスト教材修正のお願い（検索機能）

### ISSUE THREAD

**Issue by kyokucho1989** [yoshitokamizato/Gyakuten#126]
> データを登録するためのデータベースを作成します。まずは、modelを作成しましょう。modelの名前はuserにしてください。
> `rails g model user`

`rails g model user`　の前に`bundle exec rake db:create`の記述が必要だと思います。
　

> データを投入したら、検索メソッドを実装するためのモデルを作成しましょう。今回作成するモデルのファイル名は`user_search.rb`です。

`app/model/user_search.rb`　とすると場所が分かりやすいです。

　
> usersディレクトリに`search.html.erb`を作成し、以下のコードを記述しましょう。

　「viewsディレクトリ内にusersディレクトリを作成。その中に`search.html.erb`を作成し、」としたほうが分かりやすいです。

よろしくお願いします。

**Comment by T-Tsujii** [comment]
現在のransack公式に基づいて大葉に改修を行いました。
