### ISSUE TITLE
PHPのテキスト教材を表示

### ISSUE THREAD

**Issue by yoshitokamizato** [yoshitokamizato/Gyakuten#188]
- PHPテキスト教材リンクをナビバーに追加
- PHPテキスト教材データを管理画面から登録

**Comment by rod91** [comment]
- PHPテキスト教材リンクをナビバーに追加 
- 管理者画面から教材を投稿できるようにする
- 管理者画面から教材の順序を変更できるようにする
- 教材を追加する（スタイルの調整もを行う）

教材記事はこちら

https://github.com/shimotaroo/gyakuten_php

並び替えについてはRails教材の並び替え機能を真似ていただければOKと思います。

※報酬は5000円でお願いします。

どの様な仕様にするかはかみざとさん、たけさんにヒアリングして決めてみてください。

**Comment by T-Tsujii** [comment]
以下，「前者」で実装することが決まりました。（[参考リンク](https://w1581477116-8hw426585.slack.com/archives/C016H4HBV2T/p1597624348000100?thread_ts=1597319906.025100&cid=C016H4HBV2T)）

## 質問内容

「PHPテキスト教材」を「管理者画面」から「追加・並び替え」できる機能を実装するとのことですが，
こちらは「Railsのテキスト教材」の「追加・並び替え」と「同じ」ページでもよろしいでしょうか。「異なる」ページの方がよいでしょうか。

### 実装コストの比較

並び替え機能・読破済み機能の都合上，「後者」は「前者」よりも数倍以上実装コストが高くなります。

「前者」の場合，つまり，管理者画面の「PHPテキスト教材」の追加・並び替えページと「Railsのテキスト教材」の追加・並び替えページを同じとする場合は，管理者画面の修正は最低限度で済み，ユーザー側の方も「読破済み機能」を含めかなり楽に実装できます。

一方，「後者」の場合，つまり，管理者画面の「PHPテキスト教材」の追加・並び替えページと「Railsのテキスト教材」の追加・並び替えページを別とする場合は，並び替え機能・読破済み機能の都合上，共通化の難易度が非常に高くなります。少なくとも私は実装方法の全てを見通せていません。

「後者」の場合は，現在のTextモデル・テーブル・コントローラとは別に作成することで実現する方が現実的かと思いますが，その場合は「読破済み用のモデル・テーブル」もRailsテキスト教材とは別に作成する必要があります。
