### ISSUE TITLE
Railsテキスト教材のリアルタイム検索機能を追加したい

### ISSUE THREAD

**Issue by yoshitokamizato** [yoshitokamizato/Gyakuten#68]
# 理由
- 見たい教材を探すのが大変なため

**Comment by T-Tsujii** [comment]
### 必要な機能

- Railsテキスト教材のタイトルを検索候補として，リアルタイム検索できるフォーム
   - Javascriptのみで対応して下さい。（情報は全て取得済みなので，Ransackは不要）
   - Techpitを参考にして下さい。ただし，Enterキーを押したらページ遷移する機能は不要です。
   - [https://www.techpit.jp/courses/category/Ruby%20on%20Rails?banner=category-list](https://www.techpit.jp/courses/category/Ruby%20on%20Rails?banner=category-list)

- ジャンルのリアルタイム検索機能も付けてもらえるとありがたいです
   - こちらはセレクトボックスで実装して下さい
   - リアルタイム検索機能とAND検索できればなおよいです
   - おそらく，ジャンル情報がテキスト教材一覧画面に表示されていないため，data属性などにあらかじめ埋め込んでおく必要があると思います

### 注意点

- 「develop」ブランチからブランチを切るようにして下さい
