### ISSUE TITLE
管理者画面で教材の並び順を変更する機能を追加したい

### ISSUE THREAD

**Issue by yoshitokamizato** [yoshitokamizato/Gyakuten#69]
# 理由
- テキスト教材だけ実装済だが，動画教材など大部分はまだなため

**Comment by T-Tsujii** [comment]
### 注意点

基本的にはテキスト教材の真似をすればよいのですが，実装するにはいくつかの問題があります。

動画は，ほとんどが1つのモデルに入っており，ジャンルで表示を分けています。
そのため，単純に真似するだけでは対応ができません。

次の手順での実装が現実的であると思います。

- まず，Marketingモデル・コントローラをMovieにまとめる必要があります
- ジャンル順で整理できるボタンを設置する必要があります（Rails教材は複数のジャンルがあるので並び順に注意）
- その上で，テキスト教材同様，ドラッグ＆ドロップで教材の順序を入れ替える機能を付ければOKです
