### ISSUE TITLE
テキスト教材の画像（twitter:image）

### ISSUE THREAD

**Issue by yoshitokamizato** [yoshitokamizato/Gyakuten#71]
## 理由
- テキスト教材一覧の各教材の画像が同じであるため

**Comment by T-Tsujii** [comment]
こちらの`issue`ですが，データベースのデータを修正する必要があり，プルリクでは対応ができません。
そのため，私「たけ」のSlackのDMに送信していただく形式でOKです。

- 「画像」については，今後教材が追加された際に柔軟に対応できるよう，シリーズごとで背景は同じ画像を使用する形式がよいと思います。
