### ISSUE TITLE
誤記訂正願い（resourcesを使ったCRUD処理の実装）

### ISSUE THREAD

**Issue by kyokucho1989** [yoshitokamizato/Gyakuten#93]
> ここまでできたら、一度サーバーを立ち上げRailsアプリの動作を確認してみましょう。ユーザーのデータが一覧表示されていれば大丈夫です。以下のURLでアクセスしてみてください。

「以下のURL」が記載されていません。

> **削除機能の実装**
> データが一覧表示できたら、つぎにデータの削除機能を実装しましょう。まずは、views/usersディレクトリにあるindex.html.erbに削除ボタンを作成します。
> app/views/users/destroy.html.erb

app/views/users/index.html.erb
だと思います。

**Comment by T-Tsujii** [comment]
ありがとうございます！修正しました！
